update profiles & resources

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,3 +1,23 @@
 #!/bin/bash
-echo "-> Setup ubuntu";
+SCRIPT=`realpath $0`
+SCRIPTPATH=`dirname $SCRIPT`
+
+source ~/setup-ubuntu/lib/os
+
+echo $0 $1 $2
+exit
+PROFILE="$1"
+if [ "$PROFILE" == "" ]; then
+PROFILE="desktop/default"
+fi
+echo " -> Setup $DISTRO:$VERSION_ID - $PROFILE";
 echo " -----------------------------------------------------------";
+
+FILE="$SCRIPTPATH/profiles/$PROFILE/install"
+if ! test -f "$FILE"; then
+    echo " -- PROFILE NOT FOUND                                     --";
+    echo " -----------------------------------------------------------";
+    exit;
+fi
+
+./profiles/$PROFILE/install
